name: HybridWebView PR Build
on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: "PR build"
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: Clone source
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Add MSBuild to PATH (Windows)
        uses: microsoft/setup-msbuild@v1.1.3
        if: matrix.os == 'windows-latest'

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x

      - name: "Restore NuGet packages"
        run: msbuild /t:restore /p:Configuration=Release MauiCSharpInteropWebView.sln

      # - name: "Publish bin logs as artifacts"
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: msbuild-binlogs
      #     path: '**/*.binlog'
      #   if: always()

      - name: "Build and pack HybridWebView"
        run: msbuild /t:build,pack /p:Configuration=Release HybridWebView/HybridWebView.csproj

      - name: "Build sample: MauiCSharpInteropWebView"
        run: msbuild /t:build /p:Configuration=Release MauiCSharpInteropWebView/MauiCSharpInteropWebView.csproj

      - name: "Build sample: MauiReactJSHybridApp"
        run: msbuild /t:build /p:Configuration=Release MauiReactJSHybridApp/MauiReactJSHybridApp.csproj

      - name: "Publish NuGet packages as artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: nuget-packages
          path: 'artifacts/*.nupkg'
        if: matrix.os == 'windows-latest'
